### ISSUE TITLE
Rails 6.0 support

### ISSUE THREAD

**Issue by nd2go** [timberio/timber-ruby-rails#2]
HI, 

Please add Rails 6.0 support.

**Comment by stephenson** [comment]
Sitting with the same issue.

**Comment by stephenson** [comment]
@mitchellhenke @binarylogic any news on Rails 6 support? Timber is the thing holding us back from upgrading.

**Comment by stephenson** [comment]
The inactiveness of your interactions with us here is making us look for another logging supplier.
