### ISSUE TITLE
Rails 6 Support

### ISSUE THREAD

**Issue by fuzzygroup** [timberio/timber-ruby-rails#4]
Hi, 

I just tried to install and got this:

Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 6.0.0)

  In Gemfile:
    rails (~> 6)

    timber-rails (~> 1.0) was resolved to 1.0.1, which depends on
      rails (>= 3.0.0, < 6.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by dwarfmondo** [comment]
Any movement on this? We're currently referencing the master branch and that's not ideal.

**Comment by techpeace** [comment]
For the moment, this line in your `Gemfile` will work:

```ruby
gem 'timber-rails', github: 'timberio/timber-ruby-rails', branch: 'master'
```
